app/routes.py
from flask import (
    Blueprint,
    make_response,
    render_template,
    request,
    redirect,
    url_for,
    jsonify,
)
from app.template_risk import calculate_risk_level

# from app.validator import ComponentForm
from app import db
from app.models import (
    Customer,
    Manufacturer,
    Solution,
    Component,
    Template,
    TemplateSection,
    TemplateQuestion,
    TemplateRisk,
    Questionnaire,
    Section,
    Question,
    DraftStartQuestionnaire,
    DraftQuestionnaireComponent,
)

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def home():
    customers_count = Customer.query.count()
    manufacturers_count = Manufacturer.query.count()
    solutions_count = Solution.query.count()
    components_count = Component.query.count()
    return render_template(
        "dashboard.html",
        customers_count=customers_count,
        manufacturers_count=manufacturers_count,
        solutions_count=solutions_count,
        components_count=components_count,
    )


@main_blueprint.route("/customers", methods=["GET", "POST"])
def customers():
    if request.method == "POST":
        # Process the form data and add the customer to the database
        if "name" in request.form:
            customer = Customer(name=request.form["name"])
            db.session.add(customer)
            db.session.commit()
        return redirect(url_for("main.customers"))
    customers = Customer.query.all()
    return render_template("customers.html", customers=customers)


@main_blueprint.route("/customers/<int:customer_id>", methods=["DELETE"])
def delete_customer(customer_id):
    if request.method == "DELETE":
        # Process the form data and delete the customer from the database
        customer = Customer.query.get_or_404(customer_id)
        db.session.delete(customer)
        db.session.commit()
        response = jsonify(message="Cliente excluído")
        response.headers["HX-Redirect"] = url_for("main.customers")
        return response


@main_blueprint.route("/manufacturers", methods=["GET", "POST"])
def manufacturers():
    if request.method == "POST":
        # Process the form data and add the manufacturer to the database
        if "name" in request.form:
            manufacturer = Manufacturer(name=request.form["name"])
            db.session.add(manufacturer)
            db.session.commit()
        return redirect(url_for("main.manufacturers"))
    manufacturers = Manufacturer.query.all()
    return render_template("manufacturers.html", manufacturers=manufacturers)


@main_blueprint.route("/manufacturers/<int:manufacturer_id>", methods=["DELETE"])
def delete_manufacturer(manufacturer_id):
    if request.method == "DELETE":
        # Process the form data and delete the customer from the database
        manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
        db.session.delete(manufacturer)
        db.session.commit()
        response = jsonify(message="Fabricante excluído")
        response.headers["HX-Redirect"] = url_for("main.manufacturers")
        return response


@main_blueprint.route("/solutions", methods=["GET", "POST"])
def solutions():
    if request.method == "POST":
        # Process the form data and add the solution to the database
        if "name" in request.form:
            solution = Solution(
                name=request.form["name"],
                manufacturer_id=request.form["manufacturer_id"],
            )
            db.session.add(solution)
            db.session.commit()
        return redirect(url_for("main.solutions"))
    solutions = Solution.query.all()
    manufacturers = Manufacturer.query.all()
    return render_template(
        "solutions.html", solutions=solutions, manufacturers=manufacturers
    )


@main_blueprint.route("/solutions/<int:solution_id>", methods=["DELETE"])
def delete_solution(solution_id):
    if request.method == "DELETE":
        # Process the form data and delete the customer from the database
        solution = Solution.query.get_or_404(solution_id)
        db.session.delete(solution)
        db.session.commit()
        response = jsonify(message="Solução excluída")
        response.headers["HX-Redirect"] = url_for("main.solutions")
        return response


@main_blueprint.route("/components", methods=["GET", "POST"])
def components():
    if request.method == "POST":
        if "name" and "solution_id" in request.form:
            name = request.form["name"]
            solution_id = request.form["solution_id"]
            component = Component(name=name, solution_id=solution_id)
            db.session.add(component)
            db.session.commit()
            return redirect(url_for("main.components"))
    args = request.args
    if args:
        search = args.get("search", default="", type=str)
        components = (
            Component.query.filter(Component.name.ilike(f"%{search}%"))
            .order_by(Component.name)
            .all()
        )
        return render_template(
            "components/section_component.html", components=components
        )
    components = Component.query.all()
    return render_template(
        "components.html", components=components, solutions=Solution.query.all()
    )


@main_blueprint.route("/components/<int:component_id>", methods=["DELETE"])
def delete_component(component_id):
    if request.method == "DELETE":
        # Process the form data and delete the customer from the database
        component = Component.query.get_or_404(component_id)
        db.session.delete(component)
        db.session.commit()
        response = jsonify(message="Componente excluído")
        response.headers["HX-Redirect"] = url_for("main.components")
        return response


@main_blueprint.route("/components/<int:component_id>", methods=["GET", "POST"])
def component_details(component_id):
    if request.method == "POST":
        # Process the form data and update the component in the database
        if "name" in request.form:
            component = Component.query.get_or_404(component_id)
            component.name = request.form["name"]
            db.session.commit()
        return redirect(url_for("main.component_details", component_id=component_id))
    component = Component.query.get_or_404(component_id)
    return render_template("component_details.html", component=component)


@main_blueprint.route("/templates", methods=["GET", "POST"])
def templates():
    if request.method == "POST":
        # Process the form data and add the template to the database
        if "name" and "description" in request.form:
            template = Template(
                name=request.form["name"], description=request.form["description"]
            )
            db.session.add(template)
            db.session.commit()
        return redirect(url_for("main.templates"))
    templates = Template.query.all()
    return render_template("templates.html", templates=templates)


@main_blueprint.route("/templates/<int:template_id>", methods=["GET", "POST"])
def template_details(template_id):
    if request.method == "POST":
        # Process the form data and update the template in the database
        if "name" and "description" in request.form:
            template = Template.query.get_or_404(template_id)
            template.name = request.form["name"]
            template.description = request.form["description"]
            db.session.commit()
        return redirect(url_for("main.template_details", template_id=template_id))
    template = Template.query.get_or_404(template_id)
    return render_template(
        "template_details.html",
        template=template,
        template_sections=TemplateSection.query.filter_by(
            template_id=template_id
        ).all(),
        components=Component.query.all(),
    )


@main_blueprint.route("/templates/<int:template_id>/sections", methods=["GET", "POST"])
def template_sections(template_id):
    if request.method == "POST":
        # Process the form data and add the section to the database
        if "name" in request.form:
            last_section_number = (
                TemplateSection.query.filter_by(template_id=template_id)
                .order_by(TemplateSection.number.desc())
                .first()
            )
            if last_section_number:
                section_number = last_section_number.number + 1
            else:
                section_number = 1
            section = TemplateSection(
                name=request.form["name"],
                number=section_number,
                template_id=template_id,
            )
            db.session.add(section)
            db.session.commit()
        return redirect(url_for("main.template_details", template_id=template_id))
    template_sections = TemplateSection.query.filter_by(template_id=template_id).all()
    # Variável para armazenar a seção selecionada
    selected_section_id = request.args.get("selected_section_id", None, type=int)
    return render_template(
        "partials/template_sections.html",
        template_sections=template_sections,
        selected_section_id=selected_section_id,
    )
    # sections = TemplateSection.query.filter_by(template_id=template_id).all()
    # return render_template('template_details.html', template=Template.query.get_or_404(template_id), template_sections=TemplateSection.query.filter_by(template_id=template_id).all(), sections=sections)


@main_blueprint.route(
    "/templates/<int:template_id>/sections/<int:section_id>", methods=["DELETE"]
)
def delete_section(template_id, section_id):
    section = TemplateSection.query.get_or_404(section_id)
    db.session.delete(section)
    db.session.commit()
    # Retorna o cabeçalho HX-Redirect para redirecionar para 'template_details'
    response = jsonify(message="Seção excluída")
    response.headers["HX-Redirect"] = url_for(
        "main.template_details", template_id=template_id
    )
    return response

app/templates/component_details.html
{% extends "base.html" %}
{% block title %}Detalhes do Componente{% endblock %}

{% block content %}
<div class="bg-white rounded-lg shadow p-6">
    <h2 class="text-lg font-bold mb-4">Detalhes do Componente</h2>
    <form method="POST" action="/components/{{ component.id }}">
        <div class="mb-4">
            <label for="name" class="block text-gray-700">Nome do Componente</label>
            <input type="text" id="name" name="name" value="{{ component.name }}" class="w-full border border-gray-300 rounded px-3 py-2" required>
        </div>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Salvar</button>
    </form>
</div>
{% endblock %}

app/templates/components.html
{% extends "base.html" %} {% block title %}Cadastro de Componentes{% endblock %}
{% block content %}

<div class="bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden">
        <div class="px-8 py-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6">
                Cadastro de Componentes
            </h2>
            <form method="POST" action="{{ url_for('main.components') }}" class="space-y-6">
                <div class="space-y-4">
                    <div>
                        <label for="name" class="block text-gray-700">Nome</label>
                        <input type="text" id="name" name="name" class="w-full border border-gray-300 rounded px-3 py-2"
                            required />
                    </div>

                    <div>
                        <label for="solution_id">Selecione a Solução</label>
                        <select id="solution_id" name="solution_id"
                            class="w-full border border-gray-300 rounded px-3 py-2">
                            <option value="">Selecione</option>
                            {% for solution in solutions %}
                            <option value="{{ solution.id }}">
                                {{ solution.name }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="pt-4">
                    <button type="submit"
                        class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden mt-8">
        <div class="px-8 py-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6">
                Componentes Cadastrados
            </h2>
            {% if components %}
            <ul class="divide-y divide-gray-200">
                {% for component in components %}
                <li class="py-4 flex justify-between items-center">
                    {{ component.name }} - {{ component.solution.name }}
                    <button type="submit" class="bg-red-500 text-white p-2 rounded hover:bg-red-600 justify-self-end"
                        hx-delete="{{ url_for('main.delete_component', component_id=component.id)}}" hx-redirect="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                            <path fill-rule="evenodd"
                                d="M5 3.25V4H2.75a.75.75 0 0 0 0 1.5h.3l.815 8.15A1.5 1.5 0 0 0 5.357 15h5.285a1.5 1.5 0 0 0 1.493-1.35l.815-8.15h.3a.75.75 0 0 0 0-1.5H11v-.75A2.25 2.25 0 0 0 8.75 1h-1.5A2.25 2.25 0 0 0 5 3.25Zm2.25-.75a.75.75 0 0 0-.75.75V4h3v-.75a.75.75 0 0 0-.75-.75h-1.5ZM6.05 6a.75.75 0 0 1 .787.713l.275 5.5a.75.75 0 0 1-1.498.075l-.275-5.5A.75.75 0 0 1 6.05 6Zm3.9 0a.75.75 0 0 1 .712.787l-.275 5.5a.75.75 0 0 1-1.498-.075l.275-5.5a.75.75 0 0 1 .786-.711Z"
                                clip-rule="evenodd" />
                        </svg>
                    </button>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p class="text-gray-500 text-center">
                Nenhum componente cadastrado.
            </p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/customers.html
{% extends "base.html" %} {% block title %}Cadastro de Clientes{% endblock %} {%
block content %}

<div class="bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden">
        <div class="px-8 py-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6">
                Cadastro de Clientes
            </h2>
            <form action="{{ url_for('main.customers') }}" method="POST" class="space-y-6">
                <div class="space-y-4">
                    <div>
                        <label for="name" class="block text-gray-700">Nome</label>
                        <input type="text" id="name" name="name" class="w-full border border-gray-300 rounded px-3 py-2"
                            required />
                    </div>
                </div>
                <div class="pt-4">
                    <button type="submit"
                        class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden mt-8">
        <div class="px-8 py-6">
            <h2 class="text-2xl font-bold text-gray-800 mb-6">
                Clientes Cadastrados
            </h2>
            {% if customers %}
            <ul class="divide-y divide-gray-200">
                {% for customer in customers %}
                <li class="py-4 flex justify-between items-center">
                    {{ customer.name }}
                    <button type="submit" class="bg-red-500 text-white p-2 rounded hover:bg-red-600 justify-self-end"
                        hx-delete="{{ url_for('main.delete_customer', customer_id=customer.id)}}" hx-redirect="true">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                            <path fill-rule="evenodd"
                                d="M5 3.25V4H2.75a.75.75 0 0 0 0 1.5h.3l.815 8.15A1.5 1.5 0 0 0 5.357 15h5.285a1.5 1.5 0 0 0 1.493-1.35l.815-8.15h.3a.75.75 0 0 0 0-1.5H11v-.75A2.25 2.25 0 0 0 8.75 1h-1.5A2.25 2.25 0 0 0 5 3.25Zm2.25-.75a.75.75 0 0 0-.75.75V4h3v-.75a.75.75 0 0 0-.75-.75h-1.5ZM6.05 6a.75.75 0 0 1 .787.713l.275 5.5a.75.75 0 0 1-1.498.075l-.275-5.5A.75.75 0 0 1 6.05 6Zm3.9 0a.75.75 0 0 1 .712.787l-.275 5.5a.75.75 0 0 1-1.498-.075l.275-5.5a.75.75 0 0 1 .786-.711Z"
                                clip-rule="evenodd" />
                        </svg>
                    </button>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p class="text-gray-500 text-center">Nenhum cliente cadastrado.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="grid grid-cols-1 lg:grid-cols-4 gap-6">
    <!-- Clientes -->
    <div class="bg-white rounded-lg shadow p-4 flex flex-col items-center">
        <a href="/customers" class="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                <path fill-rule="evenodd"
                    d="M3 2.25a.75.75 0 0 0 0 1.5v16.5h-.75a.75.75 0 0 0 0 1.5H15v-18a.75.75 0 0 0 0-1.5H3ZM6.75 19.5v-2.25a.75.75 0 0 1 .75-.75h3a.75.75 0 0 1 .75.75v2.25a.75.75 0 0 1-.75.75h-3a.75.75 0 0 1-.75-.75ZM6 6.75A.75.75 0 0 1 6.75 6h.75a.75.75 0 0 1 0 1.5h-.75A.75.75 0 0 1 6 6.75ZM6.75 9a.75.75 0 0 0 0 1.5h.75a.75.75 0 0 0 0-1.5h-.75ZM6 12.75a.75.75 0 0 1 .75-.75h.75a.75.75 0 0 1 0 1.5h-.75a.75.75 0 0 1-.75-.75ZM10.5 6a.75.75 0 0 0 0 1.5h.75a.75.75 0 0 0 0-1.5h-.75Zm-.75 3.75A.75.75 0 0 1 10.5 9h.75a.75.75 0 0 1 0 1.5h-.75a.75.75 0 0 1-.75-.75ZM10.5 12a.75.75 0 0 0 0 1.5h.75a.75.75 0 0 0 0-1.5h-.75ZM16.5 6.75v15h5.25a.75.75 0 0 0 0-1.5H21v-12a.75.75 0 0 0 0-1.5h-4.5Zm1.5 4.5a.75.75 0 0 1 .75-.75h.008a.75.75 0 0 1 .75.75v.008a.75.75 0 0 1-.75.75h-.008a.75.75 0 0 1-.75-.75v-.008Zm.75 2.25a.75.75 0 0 0-.75.75v.008c0 .414.336.75.75.75h.008a.75.75 0 0 0 .75-.75v-.008a.75.75 0 0 0-.75-.75h-.008ZM18 17.25a.75.75 0 0 1 .75-.75h.008a.75.75 0 0 1 .75.75v.008a.75.75 0 0 1-.75.75h-.008a.75.75 0 0 1-.75-.75v-.008Z"
                    clip-rule="evenodd" />
            </svg>
            <h2 class="text-lg font-bold">Clientes</h2>
        </a>
        <span class="text-5xl">{{ customers_count }}</span>
    </div>

    <!-- Fabricantes -->
    <div class="bg-white rounded-lg shadow p-4 flex flex-col items-center">
        <a href="/manufacturers" class="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                <path
                    d="M12.378 1.602a.75.75 0 0 0-.756 0L3 6.632l9 5.25 9-5.25-8.622-5.03ZM21.75 7.93l-9 5.25v9l8.628-5.032a.75.75 0 0 0 .372-.648V7.93ZM11.25 22.18v-9l-9-5.25v8.57a.75.75 0 0 0 .372.648l8.628 5.033Z" />
            </svg>
            <h2 class="text-lg font-bold">Fabricantes</h2>
        </a>
        <span class="text-5xl">{{ manufacturers_count }}</span>
    </div>

    <!-- Soluções -->
    <div class="bg-white rounded-lg shadow p-4 flex flex-col items-center">
        <a href="/solutions" class="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                <path fill-rule="evenodd"
                    d="M10.5 3.798v5.02a3 3 0 0 1-.879 2.121l-2.377 2.377a9.845 9.845 0 0 1 5.091 1.013 8.315 8.315 0 0 0 5.713.636l.285-.071-3.954-3.955a3 3 0 0 1-.879-2.121v-5.02a23.614 23.614 0 0 0-3 0Zm4.5.138a.75.75 0 0 0 .093-1.495A24.837 24.837 0 0 0 12 2.25a25.048 25.048 0 0 0-3.093.191A.75.75 0 0 0 9 3.936v4.882a1.5 1.5 0 0 1-.44 1.06l-6.293 6.294c-1.62 1.621-.903 4.475 1.471 4.88 2.686.46 5.447.698 8.262.698 2.816 0 5.576-.239 8.262-.697 2.373-.406 3.092-3.26 1.47-4.881L15.44 9.879A1.5 1.5 0 0 1 15 8.818V3.936Z"
                    clip-rule="evenodd" />
            </svg>
            <h2 class="text-lg font-bold">Soluções</h2>
        </a>
        <span class="text-5xl">{{ solutions_count }}</span>
    </div>

    <!-- Componentes -->
    <div class="bg-white rounded-lg shadow p-4 flex flex-col items-center">
        <a href="/components" class="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                <path
                    d="M11.25 5.337c0-.355-.186-.676-.401-.959a1.647 1.647 0 0 1-.349-1.003c0-1.036 1.007-1.875 2.25-1.875S15 2.34 15 3.375c0 .369-.128.713-.349 1.003-.215.283-.401.604-.401.959 0 .332.278.598.61.578 1.91-.114 3.79-.342 5.632-.676a.75.75 0 0 1 .878.645 49.17 49.17 0 0 1 .376 5.452.657.657 0 0 1-.66.664c-.354 0-.675-.186-.958-.401a1.647 1.647 0 0 0-1.003-.349c-1.035 0-1.875 1.007-1.875 2.25s.84 2.25 1.875 2.25c.369 0 .713-.128 1.003-.349.283-.215.604-.401.959-.401.31 0 .557.262.534.571a48.774 48.774 0 0 1-.595 4.845.75.75 0 0 1-.61.61c-1.82.317-3.673.533-5.555.642a.58.58 0 0 1-.611-.581c0-.355.186-.676.401-.959.221-.29.349-.634.349-1.003 0-1.035-1.007-1.875-2.25-1.875s-2.25.84-2.25 1.875c0 .369.128.713.349 1.003.215.283.401.604.401.959a.641.641 0 0 1-.658.643 49.118 49.118 0 0 1-4.708-.36.75.75 0 0 1-.645-.878c.293-1.614.504-3.257.629-4.924A.53.53 0 0 0 5.337 15c-.355 0-.676.186-.959.401-.29.221-.634.349-1.003.349-1.036 0-1.875-1.007-1.875-2.25s.84-2.25 1.875-2.25c.369 0 .713.128 1.003.349.283.215.604.401.959.401a.656.656 0 0 0 .659-.663 47.703 47.703 0 0 0-.31-4.82.75.75 0 0 1 .83-.832c1.343.155 2.703.254 4.077.294a.64.64 0 0 0 .657-.642Z" />
            </svg>
            <h2 class="text-lg font-bold">Componentes</h2>
        </a>
        <span class="text-5xl">{{ components_count }}</span>
    </div>
</div>
{% endblock %}

app/templates/template_details.html
{% extends "base.html" %}
{% block title %}Cadastro de Clientes{% endblock %}

{% block content %}
<div class="bg-white rounded-lg shadow p-4 flex justify-between items-center gap-2">
    <div id="template_name_and_description">
        <h2 class="text-lg font-bold">{{ template.name }}</h2>
        <span class="text-gray-600 text-sm">{{ template.description }}</span>
    </div>
    <div id="template_risk_link">
        <a href="/templates/{{template.id}}/risks"
            class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Configurar riscos
        </a>
    </div>
</div>

<div class="flex gap-2">
    <aside id="sections-sidebar"
        class="bg-white rounded-lg shadow p-4 w-80 space-y-6 mt-2 max-h-[90vh] overflow-y-auto">
        <form action="/templates/{{template.id}}/sections" method="POST"
            class="flex gap-1 justify-between items-center">
            <div class="">
                <input type="text" id="name" name="name" class="w-full border border-gray-300 rounded px-2 py-1"
                    placeholder="Adicionar seção" required>
                <!-- <input type="hidden" name="template_id" value=""> -->
            </div>
            <div class="">
                <button type="submit" class="bg-blue-500 text-white px-2 py-2 rounded hover:bg-blue-600">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="size-4">
                        <path
                            d="M8.75 3.75a.75.75 0 0 0-1.5 0v3.5h-3.5a.75.75 0 0 0 0 1.5h3.5v3.5a.75.75 0 0 0 1.5 0v-3.5h3.5a.75.75 0 0 0 0-1.5h-3.5v-3.5Z" />
                    </svg>
                </button>
            </div>
        </form>
        <div id="sections" hx-trigger="load" hx-swap="innerHTML"
            hx-get="{{ url_for('main.template_sections', template_id=template.id) }}"></div>
    </aside>
    <!-- <script>
        //document.addEventListener('htmx:afterSwap', function(event) {
        // Verifica se o swap ocorreu no wrapper do select
        //const wrapper = event.target.closest('#component-select-wrapper');
        //if (wrapper) {
        //    const select = wrapper.querySelector('#component-select');
        //   if (select && select.options.length > 1) {
        //        select.selectedIndex = 1; // Seleciona o primeiro item válido
        //    }
        //}
        //});
    </script> -->
    <div class="bg-white rounded-lg shadow p-4 mt-2 w-full max-h-[90vh] overflow-auto border-box relative">
        <div id="questions" hx-trigger="load" hx-swap="innerHTML" hx-target="#questions" {% if template_sections|length>
            0 %} hx-get="{{ url_for('main.questions',
            section_id=template_sections[0].id)}}" {% endif %}>
        </div>
    </div>
</div>
{% endblock %}

app/templates/templates.html
{% extends "base.html" %} {% block title %}Cadastro de Clientes{% endblock %} {%
block content %}
<div class="bg-white rounded-lg shadow p-4">
    <h2 class="text-lg font-bold mb-2">Adicionar modelo de questionário:</h2>
    <form method="POST" action="{{ url_for('main.templates') }}">
        <div class="mb-1">
            <!--<label for="name" class="block text-gray-700">Nome</label>-->
            <input
                type="text"
                id="name"
                name="name"
                class="w-full border border-gray-300 rounded px-3 py-2 mb-1"
                placeholder="Nome do modelo"
                required
            />
            <textarea
                id="description"
                name="description"
                class="w-full border border-gray-300 rounded px-3 py-2"
                placeholder="Descrição do modelo"
            ></textarea>
        </div>
        <button
            type="submit"
            class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 flex items-center gap-2"
        >
            <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 16 16"
                fill="currentColor"
                class="size-4"
            >
                <path
                    d="M8.75 3.75a.75.75 0 0 0-1.5 0v3.5h-3.5a.75.75 0 0 0 0 1.5h3.5v3.5a.75.75 0 0 0 1.5 0v-3.5h3.5a.75.75 0 0 0 0-1.5h-3.5v-3.5Z"
                />
            </svg>
            Adicionar
        </button>
    </form>
</div>

<div class="bg-white rounded-lg shadow p-6 mt-6">
    <h2 class="text-lg font-bold mb-4">Modelos cadastrados:</h2>
    <ul>
        {% for template in templates %}
        <div class="mb-2">
            <a href="/templates/{{ template.id }}">
                <li class="py-1">{{ template.name }}</li>
                <span class="text-gray-600 text-sm"
                    >{{ template.description }}</span
                >
            </a>
            <hr />
        </div>
        {% endfor %}
    </ul>
</div>
{% endblock %}